"""
services/mlflow_tracker.py
============================

Custom MLflow telemetry module for the RAG pipeline. The official
``mlflow`` client is synchronous; every call into it is therefore
offloaded to a worker thread via :func:`asyncio.to_thread` so that
telemetry logging never blocks the async request path. Failures in
telemetry are logged and swallowed -- observability must never take
down the user-facing pipeline.

.. note::
   MLflow's tracking client is not natively thread-safe across
   concurrent runs sharing global state. This module opens a new run
   per request in an isolated thread and ensures the run is always
   terminated, which is safe for concurrent use from an async server.
"""

from __future__ import annotations

import asyncio
import logging
from contextlib import contextmanager
from typing import Iterator, List, Optional

import mlflow
from mlflow.exceptions import MlflowException

from config import settings
from schemas import CitationSchema

logger = logging.getLogger(__name__)

_client_configured = False


def _ensure_configured() -> None:
    """Idempotently configure the MLflow tracking URI and experiment.

    :raises MlflowException: If the tracking server cannot be reached
        or the experiment cannot be created/selected.
    """
    global _client_configured
    if _client_configured:
        return
    mlflow.set_tracking_uri(settings.MLFLOW_TRACKING_URI)
    mlflow.set_experiment(settings.MLFLOW_EXPERIMENT_NAME)
    _client_configured = True


@contextmanager
def _run_context(run_name: str) -> Iterator[None]:
    """Open and reliably close an MLflow run around a block of telemetry calls.

    :param run_name: Human-readable name for the run.
    :yield: Control, with an active MLflow run bound for the duration.
    """
    _ensure_configured()
    with mlflow.start_run(run_name=run_name):
        yield


class MLflowTracker:
    """Asynchronous facade over MLflow tracking for RAG pipeline telemetry."""

    def _log_query_sync(
        self,
        run_name: str,
        user_id: str,
        query: str,
        role: str,
        retrieval_latency_ms: int,
        generation_latency_ms: int,
        total_latency_ms: int,
        num_retrieved_chunks: int,
        top_relevance_score: float,
        mean_relevance_score: float,
        prompt_tokens: int,
        completion_tokens: int,
        model: str,
        citations: List[CitationSchema],
    ) -> None:
        """Synchronous MLflow logging body, executed inside a worker thread.

        :param run_name: Human-readable name for the MLflow run.
        :param user_id: Identifier of the requesting user (logged as a tag, not a param, for privacy).
        :param query: The user's query text (logged as a tag, truncated).
        :param role: The user's role, used for RBAC-aware analytics.
        :param retrieval_latency_ms: Time spent in hybrid search retrieval.
        :param generation_latency_ms: Time spent in LLM answer generation.
        :param total_latency_ms: End-to-end pipeline latency.
        :param num_retrieved_chunks: Number of chunks returned by retrieval.
        :param top_relevance_score: Highest relevance score among retrieved chunks.
        :param mean_relevance_score: Mean relevance score among retrieved chunks.
        :param prompt_tokens: Prompt tokens consumed by the LLM call.
        :param completion_tokens: Completion tokens generated by the LLM call.
        :param model: The LLM deployment name used.
        :param citations: The citations returned with the generated answer.
        """
        with _run_context(run_name):
            mlflow.set_tags(
                {
                    "user_id": user_id,
                    "role": role,
                    "model": model,
                    "query_preview": query[:200],
                }
            )
            mlflow.log_metrics(
                {
                    "retrieval_latency_ms": retrieval_latency_ms,
                    "generation_latency_ms": generation_latency_ms,
                    "total_latency_ms": total_latency_ms,
                    "num_retrieved_chunks": num_retrieved_chunks,
                    "top_relevance_score": top_relevance_score,
                    "mean_relevance_score": mean_relevance_score,
                    "prompt_tokens": prompt_tokens,
                    "completion_tokens": completion_tokens,
                    "total_tokens": prompt_tokens + completion_tokens,
                    "num_citations": len(citations),
                }
            )

    async def log_query_execution(
        self,
        user_id: str,
        query: str,
        role: str,
        retrieval_latency_ms: int,
        generation_latency_ms: int,
        num_retrieved_chunks: int,
        relevance_scores: List[float],
        prompt_tokens: int,
        completion_tokens: int,
        model: str,
        citations: Optional[List[CitationSchema]] = None,
        run_name: str = "rag-query",
    ) -> None:
        """Log a complete RAG query execution's telemetry to MLflow.

        Any failure while communicating with the MLflow tracking server
        is caught, logged, and suppressed: observability is best-effort
        and must never cause a user-facing failure of the RAG pipeline.

        :param user_id: Identifier of the requesting user.
        :param query: The user's query text.
        :param role: The user's role.
        :param retrieval_latency_ms: Time spent in hybrid search retrieval.
        :param generation_latency_ms: Time spent in LLM answer generation.
        :param num_retrieved_chunks: Number of chunks returned by retrieval.
        :param relevance_scores: Relevance scores of every retrieved chunk.
        :param prompt_tokens: Prompt tokens consumed by the LLM call.
        :param completion_tokens: Completion tokens generated by the LLM call.
        :param model: The LLM deployment name used.
        :param citations: The citations returned with the generated answer.
        :param run_name: Human-readable name for the MLflow run.
        """
        citations = citations or []
        top_score = max(relevance_scores) if relevance_scores else 0.0
        mean_score = (sum(relevance_scores) / len(relevance_scores)) if relevance_scores else 0.0

        try:
            await asyncio.to_thread(
                self._log_query_sync,
                run_name,
                user_id,
                query,
                role,
                retrieval_latency_ms,
                generation_latency_ms,
                retrieval_latency_ms + generation_latency_ms,
                num_retrieved_chunks,
                top_score,
                mean_score,
                prompt_tokens,
                completion_tokens,
                model,
                citations,
            )
        except MlflowException:
            logger.exception("MLflow telemetry logging failed (MLflow-side error); continuing without telemetry.")
        except Exception:  # noqa: BLE001 - telemetry must never break the pipeline
            logger.exception("Unexpected error while logging MLflow telemetry; continuing without telemetry.")
